In [1]:
#Procesamiento
import pandas as pd
import numpy as np
import datetime as dt
#import missingno as msno

#Visualizaci√≥n
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.graph_objects as go

In [3]:
df = pd.read_csv('./datasets/android-games.csv')
df.describe().T

,count,mean,std,min,25%,50%,75%,max
rank,1736.0,5.022005e+01,2.902510e+01,1.0,25.00,50.0,75.00,100.00
total ratings,1736.0,1.110679e+06,3.988018e+06,32993.0,174227.25,427693.5,883741.00,86273129.00
average rating,1728.0,3.906250e+00,2.955102e-01,2.0,4.00,4.0,4.00,4.00
growth (30 days),1736.0,3.206262e+02,6.008528e+03,0.0,0.10,0.5,1.70,227105.70
growth (60 days),1736.0,1.221391e+02,2.250002e+03,0.0,0.20,1.0,3.30,69441.40
price,1736.0,1.090438e-02,2.146162e-01,0.0,0.00,0.0,0.00,7.49
5 star ratings,1736.0,7.964405e+05,2.948668e+06,13975.0,126826.50,295735.5,618441.25,63546766.00
4 star ratings,1736.0,1.189283e+05,3.232236e+05,2451.0,20566.25,50851.0,101602.00,5404966.00
3 star ratings,1736.0,5.870517e+04,1.668288e+05,718.0,9609.00,24944.5,52087.00,3158756.00
2 star ratings,1736.0,2.824129e+04,9.569178e+04,266.0,4235.00,10614.5,23208.25,2122183.00
1 star ratings,1736.0,1.083608e+05,5.046927e+05,545.0,12653.00,33596.5,80105.75,12495915.00

## Verificamos cuantos datos nulos hay por columna

In [4]:
missing_values_count  = df.isna().sum()
missing_values_count

Date                0
rank                0
title               0
total ratings       0
installs            0
average rating      8
growth (30 days)    0
growth (60 days)    0
price               0
category            0
5 star ratings      0
4 star ratings      0
3 star ratings      0
2 star ratings      0
1 star ratings      0
paid                7
dtype: int64

In [6]:
# Filtramos para visualizar las filas que contengan datos nulos

df[df.isna().any(1)]

,Date,rank,title,total ratings,installs,average rating,growth (30 days),growth (60 days),price,category,5 star ratings,4 star ratings,3 star ratings,2 star ratings,1 star ratings,paid
55,2/25/2020,56,PPSSPP - PSP emulator,1396630,100.0 M,4.0,0.9,1.9,0.00,GAME ACTION,1033914,134027,67488,33534,127664,NaN
113,1/14/2020,14,Growtopia,1014301,10.0 M,3.0,0.3,0.7,0.00,GAME ADVENTURE,542530,73688,72005,51658,274417,NaN
334,2/4/2020,35,Pinball Pro,282866,10.0 M,NaN,0.0,0.0,0.00,GAME BOARD,190032,46076,23927,6933,15895,False
336,2/6/2020,37,Woody Block Puzzle ¬Æ,276518,10.0 M,4.0,0.4,0.8,0.00,GAME BOARD,195563,43630,12654,6916,17752,NaN
477,2/29/2020,60,Reigns,146718,500.0 k,4.0,0.1,0.1,2.99,GAME CARD,108356,25417,5887,2868,4187,NaN
809,3/24/2020,84,Halloween Makeup Me,56154,5.0 M,NaN,0.1,0.1,0.00,GAME EDUCATIONAL,37592,6117,3688,1999,6756,False
869,2/13/2020,44,Cytus II,111679,1.0 M,NaN,0.8,1.7,1.99,GAME MUSIC,88842,11945,4620,1947,4322,True
1584,2/28/2020,59,96%: Family Quiz,77391,1.0 M,NaN,0.0,0.0,0.00,GAME TRIVIA,46468,15506,6715,2504,6196,False
1585,2/29/2020,60,"–≠–≤—Ä–∏–∫–∞! –õ–æ–≥–∏—á–µ—Å–∫–∏–µ –ó–∞–¥–∞—á–∏, –ò–≥—Ä—ã –∏ –ì–æ–ª–æ–≤–æ–ª–æ–º–∫–∏",76857,1.0 M,4.0,0.1,0.1,0.00,GAME TRIVIA,55447,12867,2797,1049,4695,NaN
1591,3/6/2020,66,Quiz World: Play and Win Everyday!,67251,1.0 M,4.0,78.6,157.2,0.00,GAME TRIVIA,52444,3270,2133,1286,8115,NaN
1598,3/13/2020,73,Truth or Dare,61000,1.0 M,NaN,1.0,2.5,0.00,GAME TRIVIA,44911,7894,2864,1337,3992,NaN
1722,4/2/2020,93,Word Life - Connect crosswords puzzle,121222,10.0 M,NaN,4.6,10.4,0.00,GAME WORD,74343,25022,11196,3811,6848,False
1723,4/3/2020,94,Wordox ‚Äì Free multiplayer word game,120533,1.0 M,NaN,0.0,0.0,0.00,GAME WORD,74096,21404,10592,4736,9702,False
1724,4/4/2020,95,4 Fotos 1 Palavra,115437,5.0 M,NaN,0.2,0.5,0.00,GAME WORD,85169,16622,6802,1848,4994,False

Reemplazamos los valores nulos - Nan de average rating por 4

In [8]:
# .fillna -> encuentra los valores nulos y los reemplaza por el valor que le pasemos
# inplace -> para que modifique el dataframe original.

values = {"average rating" : 4}
df.fillna(value = values, inplace = True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1736 entries, 0 to 1735
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date              1736 non-null   object
 1   rank              1736 non-null   int64
 2   title             1736 non-null   object
 3   total ratings     1736 non-null   int64
 4   installs          1736 non-null   object
 5   average rating    1736 non-null   float64
 6   growth (30 days)  1736 non-null   float64
 7   growth (60 days)  1736 non-null   float64
 8   price             1736 non-null   float64
 9   category          1736 non-null   object
 10  5 star ratings    1736 non-null   int64
 11  4 star ratings    1736 non-null   int64
 12  3 star ratings    1736 non-null   int64
 13  2 star ratings    1736 non-null   int64
 14  1 star ratings    1736 non-null   int64
 15  paid              1729 non-null   object
dtypes: float64(4), int64(7), object(5)
memory usage: 217.1+ KB

Validamos los valores de la columna paid con los valores en la columna precio

In [9]:
# Recorremos el dataframe, validamos y lo modificamos

for i in range(len(df['price'])):
    if df['price'][i] != 0:
        df['paid'][i] = True
    else:
        df['paid'][i] = False

C:\Users\Jeanette\AppData\Local\Temp\ipykernel_15336\2040093112.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['paid'][i] = False
C:\Users\Jeanette\AppData\Local\Temp\ipykernel_15336\2040093112.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['paid'][i] = True

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1736 entries, 0 to 1735
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date              1736 non-null   object
 1   rank              1736 non-null   int64
 2   title             1736 non-null   object
 3   total ratings     1736 non-null   int64
 4   installs          1736 non-null   object
 5   average rating    1736 non-null   float64
 6   growth (30 days)  1736 non-null   float64
 7   growth (60 days)  1736 non-null   float64
 8   price             1736 non-null   float64
 9   category          1736 non-null   object
 10  5 star ratings    1736 non-null   int64
 11  4 star ratings    1736 non-null   int64
 12  3 star ratings    1736 non-null   int64
 13  2 star ratings    1736 non-null   int64
 14  1 star ratings    1736 non-null   int64
 15  paid              1736 non-null   object
dtypes: float64(4), int64(7), object(5)
memory usage: 217.1+ KB

In [11]:
# Podemos visualizar que ya no hay valores nulos en nuestro dataframe

In [12]:
df.isna().sum() # sumamos los valores nulos en cada columna

Date                0
rank                0
title               0
total ratings       0
installs            0
average rating      0
growth (30 days)    0
growth (60 days)    0
price               0
category            0
5 star ratings      0
4 star ratings      0
3 star ratings      0
2 star ratings      0
1 star ratings      0
paid                0
dtype: int64

### Verificamos si existen valores duplicados

In [13]:
df[df.duplicated()]

Empty DataFrame
Columns: [Date, rank, title, total ratings, installs, average rating, growth (30 days), growth (60 days), price, category, 5 star ratings, 4 star ratings, 3 star ratings, 2 star ratings, 1 star ratings, paid]
Index: []

In [14]:
df[df.duplicated(subset=['Date','rank','title','total ratings','category'], keep = False)]

,Date,rank,title,total ratings,installs,average rating,growth (30 days),growth (60 days),price,category,5 star ratings,4 star ratings,3 star ratings,2 star ratings,1 star ratings,paid
402,1/3/2020,3,Solitaire,1590733,100.0 M,4.0,0.4,0.9,0.0,GAME CARD,1117298,308402,82191,25750,57090,False
403,1/3/2020,3,Solitaire,1590733,100.0 M,4.0,0.4,0.9,0.0,GAME CARD,431463,90350,40065,15998,70189,False
404,1/3/2020,3,Solitaire,1590733,100.0 M,4.0,0.4,0.9,0.0,GAME CARD,418115,47121,16871,6574,18567,False
405,1/3/2020,3,Solitaire,1590733,100.0 M,4.0,0.4,0.9,0.0,GAME CARD,299715,68177,20617,4959,12653,False
412,1/10/2020,10,Solitaire,648068,50.0 M,4.0,0.0,0.0,0.0,GAME CARD,1117298,308402,82191,25750,57090,False
413,1/10/2020,10,Solitaire,648068,50.0 M,4.0,0.0,0.0,0.0,GAME CARD,431463,90350,40065,15998,70189,False
414,1/10/2020,10,Solitaire,648068,50.0 M,4.0,0.0,0.0,0.0,GAME CARD,418115,47121,16871,6574,18567,False
415,1/10/2020,10,Solitaire,648068,50.0 M,4.0,0.0,0.0,0.0,GAME CARD,299715,68177,20617,4959,12653,False
418,1/13/2020,13,Solitaire,507250,50.0 M,4.0,0.9,1.9,0.0,GAME CARD,1117298,308402,82191,25750,57090,False
419,1/13/2020,13,Solitaire,507250,50.0 M,4.0,0.9,1.9,0.0,GAME CARD,431463,90350,40065,15998,70189,False
420,1/13/2020,13,Solitaire,507250,50.0 M,4.0,0.9,1.9,0.0,GAME CARD,418115,47121,16871,6574,18567,False
421,1/13/2020,13,Solitaire,507250,50.0 M,4.0,0.9,1.9,0.0,GAME CARD,299715,68177,20617,4959,12653,False
427,1/19/2020,19,Solitaire,406124,10.0 M,4.0,0.3,0.7,0.0,GAME CARD,1117298,308402,82191,25750,57090,False
428,1/19/2020,19,Solitaire,406124,10.0 M,4.0,0.3,0.7,0.0,GAME CARD,431463,90350,40065,15998,70189,False
429,1/19/2020,19,Solitaire,406124,10.0 M,4.0,0.3,0.7,0.0,GAME CARD,418115,47121,16871,6574,18567,False
430,1/19/2020,19,Solitaire,406124,10.0 M,4.0,0.3,0.7,0.0,GAME CARD,299715,68177,20617,4959,12653,False
459,2/17/2020,48,Solitaire,172895,5.0 M,4.0,0.2,0.4,0.0,GAME CARD,136067,21789,6870,2356,5811,False
460,2/17/2020,48,Solitaire,172895,5.0 M,4.0,0.2,0.4,0.0,GAME CARD,121771,32009,6485,1307,3182,False
461,2/17/2020,48,Solitaire,172895,5.0 M,4.0,0.2,0.4,0.0,GAME CARD,114538,32551,6438,1309,2919,False
464,2/20/2020,51,Solitaire,164757,5.0 M,4.0,0.1,0.1,0.0,GAME CARD,136067,21789,6870,2356,5811,False
465,2/20/2020,51,Solitaire,164757,5.0 M,4.0,0.1,0.1,0.0,GAME CARD,121771,32009,6485,1307,3182,False
466,2/20/2020,51,Solitaire,164757,5.0 M,4.0,0.1,0.1,0.0,GAME CARD,114538,32551,6438,1309,2919,False
468,2/22/2020,53,Solitaire,157757,5.0 M,4.0,1.0,2.7,0.0,GAME CARD,136067,21789,6870,2356,5811,False
469,2/22/2020,53,Solitaire,157757,5.0 M,4.0,1.0,2.7,0.0,GAME CARD,121771,32009,6485,1307,3182,False
470,2/22/2020,53,Solitaire,157757,5.0 M,4.0,1.0,2.7,0.0,GAME CARD,114538,32551,6438,1309,2919,False
482,3/5/2020,65,Spider Solitaire,140758,10.0 M,4.0,0.4,1.0,0.0,GAME CARD,106869,21050,6134,1638,5065,False
483,3/5/2020,65,Spider Solitaire,140758,10.0 M,4.0,0.4,1.0,0.0,GAME CARD,94475,20067,5296,1475,4247,False
490,3/12/2020,72,Spider Solitaire,125561,10.0 M,4.0,0.8,1.7,0.0,GAME CARD,106869,21050,6134,1638,5065,False
491,3/12/2020,72,Spider Solitaire,125561,10.0 M,4.0,0.8,1.7,0.0,GAME CARD,94475,20067,5296,1475,4247,False
505,"March 26, 2020",86,Solitaire,106773,5.0 M,4.0,4.3,8.9,0.0,GAME CARD,90322,9155,3306,1009,2979,False
506,"March 26, 2020",86,Solitaire,106773,5.0 M,4.0,4.3,8.9,0.0,GAME CARD,88759,7238,2562,919,2954,False
507,"March 26, 2020",86,Solitaire,106773,5.0 M,4.0,4.3,8.9,0.0,GAME CARD,66889,11772,5441,4213,10554,False
511,"March 30, 2020",90,Solitaire,102434,10.0 M,4.0,4.7,13.1,0.0,GAME CARD,90322,9155,3306,1009,2979,False
512,"March 30, 2020",90,Solitaire,102434,10.0 M,4.0,4.7,13.1,0.0,GAME CARD,88759,7238,2562,919,2954,False
513,"March 30, 2020",90,Solitaire,102434,10.0 M,4.0,4.7,13.1,0.0,GAME CARD,66889,11772,5441,4213,10554,False
516,"April 2, 2020",93,Solitaire,98872,10.0 M,4.0,0.2,0.5,0.0,GAME CARD,90322,9155,3306,1009,2979,False
517,"April 2, 2020",93,Solitaire,98872,10.0 M,4.0,0.2,0.5,0.0,GAME CARD,88759,7238,2562,919,2954,False
518,"April 2, 2020",93,Solitaire,98872,10.0 M,4.0,0.2,0.5,0.0,GAME CARD,66889,11772,5441,4213,10554,False
1649,1/24/2020,24,Word Search,455543,10.0 M,4.0,0.1,0.3,0.0,GAME WORD,278658,96142,40301,11592,28847,False
1650,1/24/2020,24,Word Search,455543,10.0 M,4.0,0.1,0.3,0.0,GAME WORD,261241,79874,29387,6949,13159,False
1656,1/30/2020,30,Word Search,390612,50.0 M,4.0,0.1,0.1,0.0,GAME WORD,278658,96142,40301,11592,28847,False
1657,1/30/2020,30,Word Search,390612,50.0 M,4.0,0.1,0.1,0.0,GAME WORD,261241,79874,29387,6949,13159,False
1698,3/11/2020,71,Word Search,161284,10.0 M,4.0,1.0,2.2,0.0,GAME WORD,106127,23103,11207,5583,15262,False
1699,3/11/2020,71,Word Search,161284,10.0 M,4.0,1.0,2.2,0.0,GAME WORD,120322,18644,5765,1708,3417,False
1708,3/20/2020,80,Word Search,149858,10.0 M,4.0,0.0,0.1,0.0,GAME WORD,106127,23103,11207,5583,15262,False
1709,3/20/2020,80,Word Search,149858,10.0 M,4.0,0.0,0.1,0.0,GAME WORD,120322,18644,5765,1708,3417,False

Podemos observar que la diferencia entre los datos duplicados se encuentra en las variables.
- 5 star ratings
- 4 star ratings
- 3 star ratings
- 2 star ratings
- 1 star ratings

Para eliminarlos y quedar con uno de los datos podemos tomar el promedio de las variables mencionadas.

In [15]:
top_games = df.groupby(['Date','rank','title','total ratings','installs','average rating',
                        'growth (30 days)','growth (60 days)','price','category','paid'])['5 star ratings','4 star ratings',
                        '3 star ratings','2 star ratings','1 star ratings'].mean()

top_games.reset_index(inplace=True)

C:\Users\Jeanette\AppData\Local\Temp\ipykernel_15336\4218213255.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  top_games = df.groupby(['Date','rank','title','total ratings','installs','average rating',

In [16]:
top_games[top_games.duplicated(subset=['Date','rank','title','total ratings','category'], keep = False)]

Empty DataFrame
Columns: [Date, rank, title, total ratings, installs, average rating, growth (30 days), growth (60 days), price, category, paid, 5 star ratings, 4 star ratings, 3 star ratings, 2 star ratings, 1 star ratings]
Index: []

In [17]:
top_games.sample(5)

,Date,rank,title,total ratings,installs,average rating,growth (30 days),growth (60 days),price,category,paid,5 star ratings,4 star ratings,3 star ratings,2 star ratings,1 star ratings
389,1/3/2020,3,My Talking Angela,13050503,500.0 M,4.0,0.6,1.4,0.0,GAME CASUAL,False,9165205.0,1073761.0,636763.0,399662.0,1775110.0
215,1/20/2020,20,Megapolis: city building simulator. Urban stra...,1451408,50.0 M,4.0,0.2,0.3,0.0,GAME STRATEGY,False,1018102.0,214995.0,74627.0,35751.0,107932.0
713,2/19/2020,50,School Girls Simulator,643497,10.0 M,4.0,1.7,3.6,0.0,GAME SIMULATION,False,481585.0,60163.0,28340.0,15861.0,57546.0
1237,3/20/2020,80,Onmyoji Arena,338283,5.0 M,4.0,0.5,1.1,0.0,GAME STRATEGY,False,231892.0,42256.0,19681.0,10169.0,34282.0
880,2/28/2020,59,Multiplayer for Minecraft PE - MCPE Servers,791425,10.0 M,4.0,0.3,0.7,0.0,GAME ARCADE,False,534451.0,43551.0,39653.0,26844.0,146923.0

### Uniformedad de datos categoricos

In [19]:
top_games['category'] = top_games['category'].str.upper() 
# transforma todas las categorias a mayusculas

In [20]:
top_games['category'].unique()

array(['GAME SPORTS', 'BIOGRAPHY BOOK', 'GAME CASUAL', 'GAME STRATEGY',
       'GAME PUZZLE', 'GAME ACTION', 'GAME RACING', 'GAME BOARD',
       'GAME ADVENTURE', 'GAME ROLE PLAYING', 'GAME ARCADE',
       'FICTION BOOK', 'GAME SIMULATION', 'GAME MUSIC',
       'GAME EDUCATIONAL', 'GAME TRIVIA', 'GAME CARD', 'GAME CASINO',
       'GAME WORD'], dtype=object)

Podemos observar categorias que no corresponden videojuegos, esas categorias corresponden a libros
En este caso podemos eliminarlos

In [21]:
top_games = top_games[~top_games['category'].isin(['FICTION BOOK', 'BIOGRAPHY BOOK'])]

In [23]:
# Verificamos que ya no se encuentran estas categorias en nuetro dataframe

top_games['category'].unique()

array(['GAME SPORTS', 'GAME CASUAL', 'GAME STRATEGY', 'GAME PUZZLE',
       'GAME ACTION', 'GAME RACING', 'GAME BOARD', 'GAME ADVENTURE',
       'GAME ROLE PLAYING', 'GAME ARCADE', 'GAME SIMULATION',
       'GAME MUSIC', 'GAME EDUCATIONAL', 'GAME TRIVIA', 'GAME CARD',
       'GAME CASINO', 'GAME WORD'], dtype=object)

## Tipos de datos

La columna de precio es de tipo object, esta columna nos ser√° m√°s √∫til si lo pasamos a tipo int o float para futuros calculos y gr√°ficas:

In [24]:
def installs(x):
    if x[-1] == 'M':
        return(float(x[:-2])*1000000)
    else:
        return(float(x[:-2])*1000)

In [25]:
top_games['installs'] = top_games['installs'].apply(installs)

In [26]:
# Verificamos

display(top_games['installs'].unique())
display(top_games['installs'].dtype)

array([5.e+08, 1.e+09, 1.e+08, 5.e+07, 1.e+07, 5.e+06, 1.e+06, 5.e+05,
       1.e+05])

dtype('float64')

In [27]:
top_games['installs'].astype('int')

0        500000000
2       1000000000
3        500000000
4        100000000
5        500000000
           ...
1701       5000000
1702       5000000
1703       1000000
1704      10000000
1705       1000000
Name: installs, Length: 1700, dtype: int32

## Reemplazar valores de variables

Vamos a cambiar los valores de la columna que indica si el videojuegos es pago o gratis:

- Pago (True) = 1
- Gratis (False) = 0

In [28]:
top_games['paid'].unique()

array([False,  True])

In [29]:
top_games['paid'] = top_games['paid'].replace({True:1, False:0})

In [30]:
top_games['paid'].unique()

array([0, 1], dtype=int64)

## Formato de fechas

Validar el formato de la fecha y convertirlo a datetime:

In [31]:
# Unificamos el formato

top_games['Date'] = pd.to_datetime(top_games['Date']).dt.strftime('%m/%d/%Y')

In [32]:
#Validamos

display(top_games['Date'].unique())
display(len(top_games['Date'].unique()))

array(['01/01/2020', '01/10/2020', '01/11/2020', '01/12/2020',
       '01/13/2020', '01/14/2020', '01/15/2020', '01/16/2020',
       '01/17/2020', '01/18/2020', '01/19/2020', '01/02/2020',
       '01/20/2020', '01/21/2020', '01/22/2020', '01/23/2020',
       '01/24/2020', '01/25/2020', '01/26/2020', '01/27/2020',
       '01/28/2020', '01/29/2020', '01/03/2020', '01/30/2020',
       '01/31/2020', '01/04/2020', '01/05/2020', '01/06/2020',
       '01/07/2020', '01/08/2020', '01/09/2020', '02/01/2020',
       '02/10/2020', '02/11/2020', '02/12/2020', '02/13/2020',
       '02/14/2020', '02/15/2020', '02/16/2020', '02/17/2020',
       '02/18/2020', '02/19/2020', '02/02/2020', '02/20/2020',
       '02/21/2020', '02/22/2020', '02/23/2020', '02/24/2020',
       '02/25/2020', '02/26/2020', '02/27/2020', '02/28/2020',
       '02/29/2020', '02/03/2020', '02/04/2020', '02/05/2020',
       '02/06/2020', '02/07/2020', '02/08/2020', '02/09/2020',
       '03/01/2020', '03/10/2020', '03/11/2020', '03/12/2020',
       '03/13/2020', '03/14/2020', '03/15/2020', '03/16/2020',
       '03/17/2020', '03/18/2020', '03/19/2020', '03/02/2020',
       '03/20/2020', '03/21/2020', '03/22/2020', '03/23/2020',
       '03/24/2020', '03/25/2020', '03/26/2020', '03/27/2020',
       '03/28/2020', '03/29/2020', '03/03/2020', '03/30/2020',
       '03/31/2020', '03/04/2020', '03/05/2020', '03/06/2020',
       '03/07/2020', '03/08/2020', '03/09/2020', '04/01/2020',
       '04/02/2020', '04/03/2020', '04/04/2020', '04/05/2020',
       '04/06/2020', '04/07/2020', '04/08/2020', '04/09/2020'],
      dtype=object)

100

Finalizamos, guardando el dataframe para su posterior uso

In [35]:
top_games.to_csv("android_games_limpio.csv")